### ISSUE TITLE
Error for Flow.partition(key: { :elem, pos })

### ISSUE THREAD

**Issue by loguntsov** [elixir-lang/flow#17]
I have this code:

```
defmodule T do
  def hello do
    r = Flow.from_enumerable([1,2,3,4,5,6])
    |> Flow.partition()
    |> Flow.map(fn x -> { x, x } end)
    |> Flow.partition()
    |> Flow.reduce( fn -> [] end, fn a, acc -> [ a | acc ] end)
    |> Flow.emit(:state)
    |> Enum.to_list
  end
end

```
Result of this:
iex(1)> T.hello();
[[], [], [], [{4, 4}, {1, 1}], [{2, 2}, {3, 3}], [], [{6, 6}], [{5, 5}]]

I would want to spread items by key in last partition.
So i made this code:

```
defmodule T do
  def hello do
    r = Flow.from_enumerable([1,2,3,4,5,6])
    |> Flow.partition()
    |> Flow.map(fn x -> { x, x } end)
    |> Flow.partition(key: { :elem, 2 })
    |> Flow.reduce( fn -> [] end, fn a, acc -> [ a | acc ] end)
    |> Flow.emit(:state)
    |> Enum.to_list
  end
end
```
But Flow makes error for this code:

```
iex(1)> T.hello()
** (exit) exited in: GenStage.close_stream(%{#Reference<0.0.2.168> => {:subscribed, #PID<0.173.0>, :permanent, 500, 1000, 1000}, #Reference<0.0.2.169> => {:subscribed, #PID<0.174.0>, :permanent, 500, 1000, 1000}, #Reference<0.0.2.170> => {:subscribed, #PID<0.175.0>, :permanent, 500, 1000, 1000}, #Reference<0.0.2.171> => {:subscribed, #PID<0.176.0>, :permanent, 500, 1000, 1000}, #Reference<0.0.2.173> => {:subscribed, #PID<0.178.0>, :permanent, 500, 1000, 1000}, #Reference<0.0.2.174> => {:subscribed, #PID<0.179.0>, :permanent, 500, 1000, 1000}, #Reference<0.0.2.175> => {:subscribed, #PID<0.180.0>, :permanent, 500, 1000, 1000}})
    ** (EXIT) shutdown
    (gen_stage) lib/gen_stage.ex:1598: GenStage.close_stream/1
       (elixir) lib/stream.ex:1248: Stream.do_resource/5
       (elixir) lib/enum.ex:1767: Enum.reverse/2
       (elixir) lib/enum.ex:2528: Enum.to_list/1
iex(1)> 
09:30:20.432 [error] GenServer #PID<0.167.0> terminating
** (ArgumentError) argument error
    (flow) lib/flow/materialize.ex:181: anonymous fn/3 in Flow.Materialize.hash_by_key/2
    (gen_stage) lib/gen_stage/partition_dispatcher.ex:196: anonymous fn/3 in GenStage.PartitionDispatcher.dispatch/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (gen_stage) lib/gen_stage/partition_dispatcher.ex:195: GenStage.PartitionDispatcher.dispatch/3
    (gen_stage) lib/gen_stage.ex:2187: GenStage.dispatch_events/3
    (gen_stage) lib/gen_stage.ex:2410: GenStage.consumer_dispatch/7
    (gen_stage) lib/gen_stage.ex:2531: GenStage.take_pc_events/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
Last message: {:"$gen_consumer", {#PID<0.164.0>, #Reference<0.0.2.38>}, [1, 5]}
State: {%{#Reference<0.0.2.38> => nil}, %{active: [#Reference<0.0.2.38>], consumers: [#Reference<0.0.1.39>, #Reference<0.0.1.28>, #Reference<0.0.2.142>, #Reference<0.0.1.10>, #Reference<0.0.2.123>, #Reference<0.0.2.106>, #Reference<0.0.2.88>, #Reference<0.0.2.70>], done?: false, producers: %{#Reference<0.0.2.38> => #PID<0.164.0>}, trigger: #Function<2.31322697/4 in Flow.Window.Global.materialize/5>}, {2, 8}, [], #Function<33.45510982/4 in Flow.Materialize.mapper_ops/1>}

09:30:20.433 [error] GenServer #PID<0.168.0> terminating
** (ArgumentError) argument error
    (flow) lib/flow/materialize.ex:181: anonymous fn/3 in Flow.Materialize.hash_by_key/2
    (gen_stage) lib/gen_stage/partition_dispatcher.ex:196: anonymous fn/3 in GenStage.PartitionDispatcher.dispatch/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (gen_stage) lib/gen_stage/partition_dispatcher.ex:195: GenStage.PartitionDispatcher.dispatch/3
    (gen_stage) lib/gen_stage.ex:2187: GenStage.dispatch_events/3
    (gen_stage) lib/gen_stage.ex:2410: GenStage.consumer_dispatch/7
    (gen_stage) lib/gen_stage.ex:2531: GenStage.take_pc_events/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
Last message: {:"$gen_consumer", {#PID<0.164.0>, #Reference<0.0.2.43>}, [3, 4]}
State: {%{#Reference<0.0.2.43> => nil}, %{active: [#Reference<0.0.2.43>], consumers: [#Reference<0.0.1.40>, #Reference<0.0.1.29>, #Reference<0.0.2.143>, #Reference<0.0.1.11>, #Reference<0.0.2.124>, #Reference<0.0.2.107>, #Reference<0.0.2.89>, #Reference<0.0.2.71>], done?: false, producers: %{#Reference<0.0.2.43> => #PID<0.164.0>}, trigger: #Function<2.31322697/4 in Flow.Window.Global.materialize/5>}, {3, 8}, [], #Function<33.45510982/4 in Flow.Materialize.mapper_ops/1>}

09:30:20.434 [error] GenServer #PID<0.179.0> terminating
** (ArgumentError) argument error
    (flow) lib/flow/materialize.ex:181: anonymous fn/3 in Flow.Materialize.hash_by_key/2
    (gen_stage) lib/gen_stage/partition_dispatcher.ex:196: anonymous fn/3 in GenStage.PartitionDispatcher.dispatch/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (gen_stage) lib/gen_stage/partition_dispatcher.ex:195: GenStage.PartitionDispatcher.dispatch/3
    (gen_stage) lib/gen_stage.ex:2187: GenStage.dispatch_events/3
    (gen_stage) lib/gen_stage.ex:2410: GenStage.consumer_dispatch/7
    (gen_stage) lib/gen_stage.ex:2531: GenStage.take_pc_events/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
Last message: {:DOWN, #Reference<0.0.1.28>, :process, #PID<0.167.0>, {:badarg, [{Flow.Materialize, :"-hash_by_key/2-fun-1-", 3, [file: 'lib/flow/materialize.ex', line: 181]}, {GenStage.PartitionDispatcher, :"-dispatch/3-fun-0-", 3, [file: 'lib/gen_stage/partition_dispatcher.ex', line: 196]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1755]}, {GenStage.PartitionDispatcher, :dispatch, 3, [file: 'lib/gen_stage/partition_dispatcher.ex', line: 195]}, {GenStage, :dispatch_events, 3, [file: 'lib/gen_stage.ex', line: 2187]}, {GenStage, :consumer_dispatch, 7, [file: 'lib/gen_stage.ex', line: 2410]}, {GenStage, :take_pc_events, 3, [file: 'lib/gen_stage.ex', line: 2531]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 601]}]}}
State: {%{#Reference<0.0.1.26> => nil, #Reference<0.0.1.27> => nil, #Reference<0.0.1.29> => nil, #Reference<0.0.1.30> => nil, #Reference<0.0.1.31> => nil, #Reference<0.0.1.32> => nil, #Reference<0.0.1.33> => nil}, %{active: [#Reference<0.0.1.33>, #Reference<0.0.1.32>, #Reference<0.0.1.31>, #Reference<0.0.1.30>, #Reference<0.0.1.29>, #Reference<0.0.1.27>, #Reference<0.0.1.26>], consumers: [{#Reference<0.0.2.166>, #Reference<0.0.2.174>}], done?: false, producers: %{#Reference<0.0.1.26> => #PID<0.165.0>, #Reference<0.0.1.27> => #PID<0.166.0>, #Reference<0.0.1.29> => #PID<0.168.0>, #Reference<0.0.1.30> => #PID<0.169.0>, #Reference<0.0.1.31> => #PID<0.170.0>, #Reference<0.0.1.32> => #PID<0.171.0>, #Reference<0.0.1.33> => #PID<0.172.0>}, trigger: #Function<2.31322697/4 in Flow.Window.Global.materialize/5>}, {6, 8}, [], #Function<3.45510982/4 in Flow.Materialize.build_reducer/2>}

```
What is wrong in my code ?

**Comment by loguntsov** [comment]
I found the :key shoud be {:elemt, 1 } for my case.

I got my mistake. Pls close ticket.
